### ISSUE TITLE
App does not initialize

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/nr1-learn-nrql#32]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
The latest version of this app (main) does not initialize and just displays 
<img width="1038" alt="Screen Shot 2021-04-01 at 1 12 05 PM" src="https://user-images.githubusercontent.com/70179303/113349244-94b8ac80-92ec-11eb-9a8d-de01865a49f3.png">

The currently deployed version (1.3.1) is working fine.

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

## Steps to Reproduce
1. Clone the `main` branch of this repository
2. `npm install`
3. `npm run start`
4. Navigate to the local app in New Relic
5. Notice the message

[NOTE]: # ( Please be as specific as possible. )

## Expected Behaviour
The app loads without an issue.

## Relevant Logs / Console output
There were no errors in the logs.

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )
* NR1 CLI version used: @datanerd/nr1/1.32.0 darwin-x64 node-v10.16.3
* Browser name and version: Chrome 89.0.4389.90 (Official Build) (x86_64)
* Operating System and version: MacOS Big Sur 11.2.3

**Comment by goldenplec** [comment]
Thanks Alex. Replicated here. Seems to be failing locally but the version in the New Relic app catalog works just fine. 

Looks like the query for accounts is returning NULL, but the query ran independently against the account returns results fine. Investigating to see why this weirdness might be happening.

**Comment by goldenplec** [comment]
@aswanson-nr looks like it may just be a New Relic staff impact. If you remove your profile and regenerate it in your CLI. It began working again for me no problem.

**Comment by aswanson-nr** [comment]
@goldenplec You were completely right! Looks like it was user error! Sorry to take up your time.
